apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ticket-selling
data:
  NODE_ENV: production
  APP_ENV: aws
  PORT: "3000"
  AWS_REGION: __AWS_REGION__
  REDIS_URL: "__REDIS_URL__"
  SQS_AUTH_QUEUE_URL: "__SQS_AUTH_QUEUE_URL__"
  SQS_CLIENT_QUEUE_URL: "__SQS_CLIENT_QUEUE_URL__"
  SQS_TICKETS_QUEUE_URL: "__SQS_TICKETS_QUEUE_URL__"
  SQS_ORDERS_SERVICE_QUEUE_URL: "__SQS_ORDERS_SERVICE_QUEUE_URL__"
  SQS_ORDER_EVENTS_QUEUE_URL: "__SQS_ORDER_EVENTS_QUEUE_URL__"
  SQS_EXPIRATION_QUEUE_URL: "__SQS_EXPIRATION_QUEUE_URL__"
  SQS_EXPIRATION_EVENTS_QUEUE_URL: "__SQS_EXPIRATION_EVENTS_QUEUE_URL__"
  SQS_PAYMENT_EVENTS_QUEUE_URL: "__SQS_PAYMENT_EVENTS_QUEUE_URL__"
  ENABLE_AUTH_WORKER: "true"
  ENABLE_CLIENT_WORKER: "true"
  ENABLE_TICKETS_WORKER: "true"
  ENABLE_ORDERS_WORKER: "true"
  ENABLE_SQS_CONSUMER: "true"
  ENABLE_EXPIRATION_WORKER: "true"
  EXPIRATION_DELAY_SECONDS: "60"
  SQS_MAX_MESSAGES: "5"
  SQS_WAIT_TIME_SECONDS: "10"
  SQS_VISIBILITY_TIMEOUT: "30"
  SQS_POLL_SLEEP_MS: "2000"
