apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: ticket-selling
  annotations:
    eks.amazonaws.com/role-arn: __AUTH_IRSA_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-sa
  namespace: ticket-selling
  annotations:
    eks.amazonaws.com/role-arn: __CLIENT_IRSA_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tickets-sa
  namespace: ticket-selling
  annotations:
    eks.amazonaws.com/role-arn: __TICKETS_IRSA_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  namespace: ticket-selling
  annotations:
    eks.amazonaws.com/role-arn: __ORDERS_IRSA_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-sa
  namespace: ticket-selling
  annotations:
    eks.amazonaws.com/role-arn: __PAYMENTS_IRSA_ROLE_ARN__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expiration-sa
  namespace: ticket-selling
  annotations:
    eks.amazonaws.com/role-arn: __EXPIRATION_IRSA_ROLE_ARN__
